# Generated by Django 5.0.6 on 2024-06-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year_founded', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='aboutus',
            name='history',
            field=models.TextField(default='Nuestra historia es un recorrido de éxitos en el apoyo a emprendedores.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mission',
            field=models.TextField(default='Nuestra misión es apoyar a los emprendedores.'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='helped_companies',
            field=models.ManyToManyField(to='core.helpedcompany'),
        ),
    ]
